version: '3.3'

services:
  database:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: "${DB_NAME}"
      PGDATA: /data/postgres
    networks:
      - bookstore-internal

  book-service:
    build: ./
    restart: unless-stopped
    ports:
      - "127.0.0.1:${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - database
    environment:
      SPRING_R2DBC_URL: "${DB_URL}"
      SPRING_R2DBC_USERNAME: "${DB_USER}"
      SPRING_R2DBC_PASSWORD: "${DB_PASS}"
      SERVER_PORT: "${SERVER_PORT}"
    networks:
      - bookstore-internal

networks:
  bookstore-internal: