server:
  port: 8443
  ssl:
    key-store: classpath:springboot.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: springboot
    key-password: password
spring:
  main:
    banner-mode: off
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/reactive-book-store
    username:
    password:
    pool:
      enabled: true
      initial-size: 5
      max-size: 10
logging:
  level:
    org:
      springframework:
        security:
          web:
            server:
              authorization:
                DelegatingReactiveAuthorizationManager: debug
                AuthorizationWebFilter: debug